version: "3"  
  
services:  
  rabbitmq:  
    image: rabbitmq:3-management  
    container_name: rabbitmq-server  
    ports:  
      - "5672:5672"   # AMQP port  
      - "15672:15672" # Management UI  
    environment:  
      RABBITMQ_DEFAULT_USER: guest  
      RABBITMQ_DEFAULT_PASS: guest  
    restart: always  
  
  consul:  
    image: consul:1.15.4  
    container_name: consul  
    ports:  
      - "8500:8500"  
      - "8601:8600/udp"  
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"  
    restart: always